import os

# Environment variables
#Azure_blob
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
AZURE_BLOB_CONTAINER_NAME_UPLOADS = os.getenv("AZURE_BLOB_CONTAINER_NAME_UPLOADS")
#Generate PDF
AZURE_BLOB_CONTAINER_NAME_REPORTS = os.getenv("AZURE_BLOB_CONTAINER_NAME_REPORTS")
#Azure_openai
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_MODEL_NAME_CHAT = os.getenv("AZURE_OPENAI_MODEL_NAME_CHAT")
AZURE_OPENAI_MODEL_NAME_EMBEDDING = os.getenv("AZURE_OPENAI_MODEL_NAME_EMBEDDING")
AZURE_OPENAI_SUBSCRIPTION_KEY = os.getenv("AZURE_OPENAI_SUBSCRIPTION_KEY")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
#Azure cosmos db
COSMOS_ENDPOINT = os.getenv("COSMOS_ENDPOINT")
COSMOS_KEY = os.getenv("COSMOS_KEY")
DATABASE_NAME = os.getenv("DATABASE_NAME")
DOCUMENT_CONTAINER_NAME = os.getenv("DOCUMENT_CONTAINER_NAME")
EMBEDDING_CONTAINER_NAME = os.getenv("EMBEDDING_CONTAINER_NAME")
COMPARISON_CONTAINER_NAME = os.getenv("COMPARISON_CONTAINER_NAME")
CHAT_CONTAINER_NAME = os.getenv("CHAT_CONTAINER_NAME")
#Formrecognition
AZURE_FORM_RECOGNIZER_ENDPOINT = os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT")
AZURE_FORM_RECOGNIZER_KEY = os.getenv("AZURE_FORM_RECOGNIZER_KEY") 